services:
  mysql:
    env_file:
      - docker.env
    container_name: frankit
    image: ubuntu/mysql:edge
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp=1
    ports:
      - 3306:3306
    environment:
      - TZ=UTC
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d